### ISSUE TITLE
Dapr runtime for functions

### ISSUE THREAD

**Issue by lance** [knative/func#1427]
@salaboy please add here sub-tasks or other descriptive information

**Comment by yaron2** [comment]
Hi, Dapr maintainer here 👋 

Happy to help if needed.

**Comment by salaboy** [comment]
Hi folks, I've did some experiments with Dapr that I've published here: 
https://salaboy.com/2022/12/24/dapr-and-knative-functions/

I've identified a set of things that we can be doing from the Knative Functions side: 
- [] Use the push gateway from prometheus to push metrics instead of using Prometheus scraping
- [] have templates for Dapr functions on the func-tastic repository
- [] Experiment with Dapr and Deamonset sidecar as done in OpenFunction project -> https://openfunction.dev/docs/concepts/baas_integration/#dapr-standalone-mode

**Comment by lkingland** [comment]
Update that as of PR #1518
- Functions now support the Dapr runtime when deployed
- Dapr is installed in CI/CD for the included integration tests
- The `allocate.sh` script (which can be used locally) sets up a Redis-backed Pub/Sub and State Storage components byu default.
- Dapr metrics are being served, and are served from port 9092 such that they do not interfere with our existing metrics integration.
