### ISSUE TITLE
Scaffolding (with Host Builder)

### ISSUE THREAD

**Issue by lkingland** [knative/func#1939]
As is outlined in the [Scaffolded Functions Discussion](https://github.com/knative/func/discussions/1589), the `host` builder is now available for Go HTTP functions and utilizes the described Scaffolding method.  This can serve as a starting point for implementation the system for our core language runtimes.

Below is an initial list (WIP)

## Go
- [x] Go HTTP Scaffolding
- [ ] Go Cloudevent Scaffolding (partially complete)
- [ ] Utilize Scaffolding in Go Pack builds
- [ ] Utilize Scaffolding in Go S2I builds
- [ ] Ensure Go Functions now work in on-cluster builds

## Python
- [ ] Python HTTP Scaffolding
- [ ] Python Cloudevent Scaffolding
- [ ] Utilize Scaffolding in Python Pack builds
- [ ] Utilize Scaffolding in Python S2I builds

## JS
- [ ] JS HTTP Scaffolding
- [ ] JS Cloudevent Scaffolding
- [ ] Utilize Scaffolding in JS Pack builds
- [ ] Utilize Scaffolding in JS S2I builds

## Java
- [ ] Java HTTP Scaffolding
- [ ] Java Cloudevent Scaffolding
- [ ] Utilize Scaffolding in Java Pack builds
- [ ] Utilize Scaffolding in Java S2I builds

## Rust
- [ ] Rust HTTP Scaffolding
- [ ] Rust Cloudevent Scaffolding
- [ ] Utilize Scaffolding in Rust Pack builds
- [ ] Utilize Scaffolding in Rust S2I builds

## Other
- [ ] Custom Base Images
- [ ] User documentation
- [ ] Developer documentation
- [ ] E2E Tests

## Related
-[ ] #1839
