### ISSUE TITLE
Automation Update

### ISSUE THREAD

**Issue by lkingland** [knative/func#2035]
Our primary repository's automation is flaky, has several actions with overlapping functionality, and local make targets have diverged from those run in CI.  In general we should probably:

- [ ] Refactor integration with codecov (it appears the integration is probabalistic and often fails to report a large chunk of the coverage, resulting in manual overrides)
- [ ] Remove Functions-specific actions which are now covered by the Knative common tooling.
- [ ] Update the Makefile targets to run the internals of these tests as closely as possible locally (i.e. `make test` should be effectively equialent to the GitHub Action, ideally running the same script if possible. This would, for example run linters with the same options locally as in CI).
- [ ] Transition to using the shared Knatve quick-start for allocating the cluster, in hopes it is less flaky (cluster allocation often fails with timeouts due to apparently having allocated resources of a potato).
- [ ] Update the build/test flags to be test with or without integration tests, rather than the current configuration of disjunct sets.
- [ ] Review our E2E tests to identify areas of possible optimization
- [ ] Investigate if we can disable the Prow bot's auto-assign of reviewers
