### ISSUE TITLE
On-cluster Builds

### ISSUE THREAD

**Issue by omerbensaadon** [knative/func#620]
WIP Design Doc: https://docs.google.com/document/d/1iQFVtfsrYb4pp616h3B_IXQB1Cck1oxt7ypZyU8ChzE/edit

Features:
Pushing code from local machine to an on-cluster build
Pushing code from Github to an on-cluster build

# Tasks required for MVP:
- [x] #748
- [x] #750
- [x] #751
- [x] #752
- [x] #753
- [x] #754
- [x] #847
- [x] #848
- [x] #765
- [x] #855
- [x] #1173
- [ ] #984
- [ ] #849
- [x] #856
- [x] #858
- [ ] #859
- [x] #852
- [x] #851
- [x] #857
- [x] #1192
- [ ] https://github.com/knative/func/issues/1858
- [ ] https://github.com/knative/func/issues/1859
# Tasks not required for MVP:
- [x] #989
- [ ] #850
- [ ] #854
- [ ] #853
- [x] #791
- [x] #952
- [x] https://github.com/knative/func/issues/1323

**Comment by salaboy** [comment]
@zroubalik I would like to take these one: 
-  On-cluster build: Implement --git flag for func deploy

I don't seem to be able to convert it to an issue from here, can you?

**Comment by omerbensaadon** [comment]
@salaboy converted for ya, check #765

**Comment by lance** [comment]
@omerbensaadon welcome back! :)

**Comment by senthilnathan** [comment]
If it is possible, can all the outstanding tasks be converted to issues by someone with the permission?

**Comment by lance** [comment]
@zroubalik do you think this can be refined and/or closed given the move to PAC?

**Comment by lkingland** [comment]
This epic is now in bug-fix/enhancement mode
