### ISSUE TITLE
On-cluster build: E2E test for build from Git repository (public & private)

### ISSUE THREAD

**Issue by lance** [knative/func#856]
- [x] Deploy on cluster a default function from a public git repository, from a default branch
- [x] Deploy on cluster a default function from a public git repository, from a feature branch
- [x] Deploy on cluster a default function from a public git repository, from a commit hash
- [x] Deploy on cluster a default function from a public git repository, from a tag revision
- [x] Deploy on cluster a default function located in a specific directory from a public git repository, from main branch
- [x] Updated changes to a function get deployed
- [x] Deploy on cluster a default function for each language: node, go, python, quarkus, springboot, typescript using pack
- [x] Deploy on cluster a default function using s2i builder for the languages supported by s2i. 
- [x] Deploy on cluster a fuction from a public GitHub repository
- [ ] Deploy on cluster a fuction from a public GitLab repository
- [ ] Deploy on cluster a default function from a Private git repository using basic http auth
- [ ] Deploy on cluster a default function from a Private git repository using ssh auth
- [x] Triggers on cluster build from cli when func.yaml indicates local
- [x] Triggers on cluster build from cli when func.yaml indicates local from a specific branch
- [x] Triggers on cluster build from cli when func.yaml indicates local from a when a functions is on a specific directory
- [x] Triggers local build from cli when func.yaml indicates build from git
- [x] Ensure all resources created by on cluster build are deleted when the functions is deleted

**Comment by lance** [comment]
@jrangelramos thanks for providing these. I've added them all to the issue description as tasks (which could potentially be turned in to github issues if you want), and added the `Epic` label. As you find other test cases, feel free to just update the main issue description if you can.

**Comment by zroubalik** [comment]
We should add tests covering s2i build strategy for on cluster build.

**Comment by lance** [comment]
@jrangelramos any updates on this?

**Comment by jrangelramos** [comment]
Hi @lance . yes I just updated the description. I shall re-take the remaining tests. Including s2i one this week still.. and may have an implementation next week probably.

**Comment by lance** [comment]
@jrangelramos do you have any update on this one?

**Comment by jrangelramos** [comment]
yes.. that item from GitHub repo is done..

For this one, I'm not seing much benefit on implement this, and thinking about remove it.
[ ] Deploy on cluster a fuction from a public GitLab repository

These remaing 2 depends on features not yet implemented in func.
[ ] Deploy on cluster a default function from a Private git repository using basic http auth
[ ] Deploy on cluster a default function from a Private git repository using ssh auth

**Comment by lance** [comment]
I agree that GitLab tests can be deferred, and the private auth for GitHub could possibly be tracked in another issue so this one can be considered complete. WDYT?

**Comment by jrangelramos** [comment]
I agree! I see no benefit on keeping this one opened for so long.

**Comment by lkingland** [comment]
I am closing this as complete (see thread).  We can of course implement E2E tests for private git repositories with http and ssh auth when those features are implemented.  Thanks for the tests Jefferson!
